//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by KWResearchWork.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_ControlPanel                101
#define IDR_MAINFRAME                   128
#define IDR_KWResearchWorkTYPE          129
#define IDR_TOOLBAR                     142
#define IDC_ZOOM                        146
#define IDC_MOVE                        147
#define IDC_CURSOR3                     148
#define IDC_ROTATE                      148
#define IDC_PAINTROI                    160
#define IDC_SMOOTH                      161
#define IDD_CP_General                  163
#define IDD_CP_Creation                 164
#define IDD_CP_Deformation              165
#define IDD_CP_Extrusion                166
#define IDD_CP_Cutting                  167
#define IDD_CP_Smoothing                168
#define IDI_ICON1                       168
#define IDD_Test                        169
#define IDD_CP_Test                     169
#define IDI_SaveFile                    169
#define IDI_NewFile                     170
#define IDD_CP_Editing                  170
#define IDI_OpenFile                    171
#define IDI_ViewMode                    172
#define IDI_ICON3                       173
#define IDI_SelMode                     173
#define IDI_ICON2                       174
#define IDI_SketchMode                  174
#define IDC_PENCIL                      178
#define IDC_SETPARA                     1012
#define IDC_SLIDER_LIGHTPOS_X           1013
#define IDC_SLIDER_LIGHTPOS_Y           1014
#define IDC_SLIDER_LIGHTPOS_Z           1015
#define IDC_SLIDER_COLOR_RED            1016
#define IDC_SLIDER_COLOR_GREEN          1017
#define IDC_SLIDER_COLOR_BLUE           1018
#define IDC_GenerateMesh                1019
#define IDC_Deform                      1020
#define IDC_Extrude                     1021
#define IDC_BUTTON1                     1021
#define IDC_DE_INTERPOLATION            1021
#define IDC_TE_Filter                   1021
#define IDC_GE_Exp_Sce_Para             1021
#define IDC_Subdivision                 1022
#define IDC_TE_Resample                 1022
#define IDC_GE_Imp_Sce_Para             1022
#define IDC_LaplacianSmooth             1023
#define IDC_TE_Smooth                   1023
#define IDC_SnapShot                    1024
#define IDC_TaubinLambdaMuSmooth        1025
#define IDC_ComputeDualMesh             1026
#define IDC_BilateralSmooth             1027
#define IDC_AdjustContourView           1028
#define IDC_ReadContour                 1029
#define IDC_CREATION_BLUEPLANE          1030
#define IDC_CREATION_GREENPLANE         1031
#define IDC_CREATION_REDPLANE           1032
#define IDC_WireFrame                   1033
#define IDC_DEFORMATION_BASICPLANE      1034
#define IDC_Hybrid                      1035
#define IDC_WriteContour                1036
#define IDC_DEFORMATION_TANGENTIALPLANE 1037
#define IDC_DEFORMATION_BINORMALPLANE   1038
#define IDC_DEFORMATION_BASICPLANE2     1039
#define IDC_DEFORMATION_REFSPHERE       1039
#define IDC_Points                      1040
#define IDC_ComputeEdgelMesh            1041
#define IDC_ComputeEdgeMesh             1041
#define IDC_ShowStren                   1043
#define IDC_TAB1                        1044
#define IDC_CP_TAB                      1044
#define IDC_GE_SLIDER_LIGHTPOS_X        1045
#define IDC_GE_SLIDER_LIGHTPOS_Y        1046
#define IDC_GE_SLIDER_LIGHTPOS_Z        1047
#define IDC_GE_SLIDER_COLOR_RED         1048
#define IDC_GE_SLIDER_COLOR_GREEN       1049
#define IDC_GE_SLIDER_COLOR_BLUE        1050
#define IDC_GE_WireFrame                1051
#define IDC_GE_SMOOTH                   1052
#define IDC_GE_Hybrid                   1053
#define IDC_GE_Points                   1054
#define IDC_GE_Subdivision              1055
#define IDC_GE_SnapShot                 1056
#define IDC_CR_BLUEPLANE                1057
#define IDC_CR_GREENPLANE               1058
#define IDC_CR_REDPLANE                 1059
#define IDC_CR_ReadContour              1060
#define IDC_CR_WriteContour             1061
#define IDC_CR_AdjustContourView        1062
#define IDC_CR_GenerateMesh             1063
#define IDC_DE_BASICPLANE               1064
#define IDC_GE_PREMESH                  1064
#define IDC_CR_CN                       1064
#define IDC_DE_TANGENTIALPLANE          1065
#define IDC_CR_SS                       1065
#define IDC_DE_BINORMALPLANE            1066
#define IDC_CR_US                       1066
#define IDC_DE_REFSPHERE                1067
#define IDC_CR_AUTOROT                  1067
#define IDC_DE_Deform                   1069
#define IDC_DE_ComputeDualMesh          1070
#define IDC_DE_ComputeEdgeMesh          1071
#define IDC_DE_ClearROI                 1072
#define IDC_DE_SLIDER_ROI               1073
#define IDC_DE_ITERNUM                  1074
#define IDC_DE_LAMBDA                   1075
#define IDC_DE_ITER_LAMBDA              1076
#define IDC_DE_ShowHandle               1077
#define IDC_DE_ShowMat                  1078
#define IDC_EX_Extrude                  1079
#define IDC_DE_SLIDER_Material          1079
#define IDC_SM_BilateralSmooth          1080
#define IDC_DE_ShowROI                  1080
#define IDC_SM_LaplacianSmooth          1081
#define IDC_DE_ShowAnchor               1081
#define IDC_SM_TaubinLambdaMuSmooth     1082
#define IDC_GE_Axis                     1084
#define IDC_DE_Material_Value           1085
#define IDC_DE_COMBO_MatSetWay          1086
#define IDC_DE_SetMat                   1087
#define IDC_MOD_ALGO_TJ                 1088
#define IDC_MOD_ALGO_PROG               1089
#define IDC_CR_COMBO_S                  1090
#define IDC_CR_COMBO_SINGLEPOLY         1090
#define IDC_CR_COMBO_SINGLESS           1091
#define IDC_CR_COMBO_SINGLEPOLY2        1092
#define IDC_CR_COMBO_UNIONPOLY          1092
#define ID_VIEW_3DAXISON                32773
#define ID_VIEW_BEST                    32775
#define ID_VIEW_BFPLANE                 32776
#define ID_OPERATION_SETRANGE           32779
#define ID_OPERATION_SUBDIVIDEFACES     32780
#define ID_OPERATION_SUBDIVISION        32781
#define ID_BUTTON32782                  32782
#define ID_BUTTON32783                  32783
#define ID_BUTTON32788                  32788
#define ID_BUTTON32789                  32789
#define ID_BUTTON32790                  32790
#define ID_BUTTON32794                  32794
#define ID_OPERATION_EXTRUDE            32798
#define ID_OPERATION_GENERATEMESH       32799
#define ID_MODE_CREATION                32801
#define ID_MODE_DEFORMATION             32802
#define ID_MODE_EXTRUSION               32803
#define ID_MODE_CUTTING                 32804
#define ID_VIEW_CURVATURE               32805
#define ID_CURVATURE_MEANCURVATURE      32806
#define ID_CURVATURE_GAUSSIAN           32807
#define ID_CURVATURE_GAUSSIANCURVATURE  32808
#define ID_OPERATION_DEFORM             32809
#define ID_OPERATION_DEFORMATION        32810
#define ID_CURVATURE_NONE               32811
#define ID_OPERATION_LAPLACIANSMOOTH    32812
#define ID_OPERATION_SNAPSHOT           32813
#define ID_MODE_SMOOTHING               32814
#define ID_OPERATION_TAUBINLAMBDAMUSMOOTH 32815
#define ID_VIEW_DUALMESH                32816
#define ID_DEFORMATION_COMPUTEDUALMESH  32817
#define ID_OPERATION_DEFORMATION_COMPUTEDUALMESH 32818
#define ID_VIEW_MESH                    32819
#define ID_MESH_PRIMALMESH              32820
#define ID_VIEW_PRIMALMESH              32821
#define ID_HELP_TEST                    32822
#define ID_DEFORMATION_INTERPOLATION    32823
#define ID_INTERPOLATION_LINEAR         32824
#define ID_DEFORMATION_INTERPOLATION_LINEAR 32825
#define ID_OPERATION_DEFORMATION_INTERPOLATION_LINEAR 32826
#define ID_DEFORMATION_INTERPOLATION32827 32827
#define ID_DEFORMATION_INTERPOLATION32828 32828
#define ID_OPERATION_DEFORMATION_INTERPOLATION 32829
#define ID_MODE_TEST                    32832
#define ID_OPERATION_LINEPREPROC        32833
#define ID_LINEPREPROC_FILTER           32834
#define ID_LINEPREPROC_RESAMPLE         32835
#define ID_LINEPREPROC_SMOOTH           32836
#define ID_OPERATION_ADJUSTCONTOURVIEW  32837
#define ID_OPERATION_CREATION           32838
#define ID_VIEW_SELECT_MODE             32839
#define ID_SKETCH_MODE                  32841
#define ID_MODE_EDITING                 32844

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        179
#define _APS_NEXT_COMMAND_VALUE         32845
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
